%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(im_pb).
-define(im_pb, true).

-define(im_pb_gpb_version, "4.18.0").

-ifndef('COMMAND_PB_H').
-define('COMMAND_PB_H', true).
-record('Command',
        {version = 0            :: integer() | undefined, % = 1, optional, 32 bits
         command = 'CONNECT'    :: 'CONNECT' | 'DISCONNECT' | 'REQUEST' | 'RESPONSE' | integer() | undefined, % = 2, optional, enum CommandType
         payload = <<>>         :: iodata() | undefined % = 3, optional
        }).
-endif.

-ifndef('CONNECT_PB_H').
-define('CONNECT_PB_H', true).
-record('Connect',
        {org = <<>>             :: unicode:chardata() | undefined, % = 1, optional
         appkey = <<>>          :: unicode:chardata() | undefined, % = 2, optional
         user = <<>>            :: unicode:chardata() | undefined, % = 3, optional
         token = <<>>           :: unicode:chardata() | undefined % = 4, optional
        }).
-endif.

-ifndef('DISCONNECT_PB_H').
-define('DISCONNECT_PB_H', true).
-record('Disconnect',
        {code = 0               :: integer() | undefined, % = 1, optional, 32 bits
         reason = <<>>          :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('OPTION_PB_H').
-define('OPTION_PB_H', true).
-record('Option',
        {offline = false        :: boolean() | 0 | 1 | undefined % = 1, optional
        }).
-endif.

-ifndef('REQUEST_PB_H').
-define('REQUEST_PB_H', true).
-record('Request',
        {type = 'MESSAGE'       :: 'MESSAGE' | 'CONTACT' | 'GROUP' | integer() | undefined, % = 1, optional, enum RequestType
         payload = <<>>         :: iodata() | undefined, % = 2, optional
         opts = []              :: [im_pb:'Option'()] | undefined % = 3, repeated
        }).
-endif.

-ifndef('MESSAGETXT_PB_H').
-define('MESSAGETXT_PB_H', true).
-record('MessageTxt',
        {txt = <<>>             :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('MESSAGEIMG_PB_H').
-define('MESSAGEIMG_PB_H', true).
-record('MessageImg',
        {url = <<>>             :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('MESSAGE_PB_H').
-define('MESSAGE_PB_H', true).
-record('Message',
        {type = 'TXT'           :: 'TXT' | 'IMAGE' | integer() | undefined, % = 1, optional, enum MessageType
         payload = <<>>         :: iodata() | undefined % = 2, optional
        }).
-endif.

-ifndef('RESPONSE_PB_H').
-define('RESPONSE_PB_H', true).
-record('Response',
        {code = 0               :: integer() | undefined, % = 1, optional, 32 bits
         reason = <<>>          :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-endif.
